In [1]:
import scipy.io as sio
import numpy as np

In [5]:
mat_contents = sio.loadmat("../data/RawContinuousRecording/U01_E01/AmazonEchoPlus/Continuous_Data_Collection-20250509134712_AmazonEchoPlus_5G.mat")
print(mat_contents.keys())

dict_keys(['__header__', '__version__', '__globals__', 'csi_trace', 'band'])


In [18]:
csi = mat_contents["csi_trace"]["csi"][0, 0]
csi

array([[[[  472.+1140.j,   181.-1215.j,   966. -831.j, ...,
          -1101. -576.j,  -709.-1054.j,  1088. +595.j],
         [ 1836. +923.j,  -757.-1926.j,   558.-2012.j, ...,
          -2062.  +79.j, -1924. -732.j,  1914. -767.j],
         [ 1825.-1301.j, -2032.-1064.j, -1247.-1868.j, ...,
          -1586.+1581.j, -1906.+1263.j,  -600.-2168.j],
         ...,
         [ -987. -464.j,   445. -967.j,  -677. -856.j, ...,
           -937. -496.j,  -205.+1020.j,   -20.-1064.j],
         [   19.  -93.j,    23.   +3.j,     6.  -25.j, ...,
             33.  -60.j,  -100.   +9.j,    39.   +4.j],
         [  317. -361.j,   131. +431.j,   463.  -16.j, ...,
            459. -128.j,  -376. -325.j,   485. -152.j]],

        [[ -673. -170.j,   475. +486.j,     3. +677.j, ...,
            622. -284.j,   671.  +42.j,  -599. +265.j],
         [ -425. +430.j,   563.   +0.j,   478. +333.j, ...,
            158. -570.j,   385. -440.j,    17. +563.j],
         [ 1047.  -75.j,  -540. -908.j,   -13.-1029.j, .

In [19]:
real_csi = np.real(csi)
imag_csi = np.imag(csi)

In [20]:
real_csi

array([[[[  472.,   181.,   966., ..., -1101.,  -709.,  1088.],
         [ 1836.,  -757.,   558., ..., -2062., -1924.,  1914.],
         [ 1825., -2032., -1247., ..., -1586., -1906.,  -600.],
         ...,
         [ -987.,   445.,  -677., ...,  -937.,  -205.,   -20.],
         [   19.,    23.,     6., ...,    33.,  -100.,    39.],
         [  317.,   131.,   463., ...,   459.,  -376.,   485.]],

        [[ -673.,   475.,     3., ...,   622.,   671.,  -599.],
         [ -425.,   563.,   478., ...,   158.,   385.,    17.],
         [ 1047.,  -540.,   -13., ..., -1024., -1082.,   300.],
         ...,
         [-1967.,  -375., -1952., ..., -1979.,   876., -1174.],
         [  262.,  -485.,   -35., ...,    92.,   413.,  -103.],
         [  512.,   143.,   701., ...,   691.,  -528.,   695.]],

        [[ 1283., -1213.,  -567., ...,  -847., -1227.,   880.],
         [ 1022., -1705., -1577., ...,  -244.,  -936.,  -350.],
         [-1069.,  -519., -1170., ...,  1237.,  1043., -1428.],
        

In [21]:
imag_csi

array([[[[ 1140., -1215.,  -831., ...,  -576., -1054.,   595.],
         [  923., -1926., -2012., ...,    79.,  -732.,  -767.],
         [-1301., -1064., -1868., ...,  1581.,  1263., -2168.],
         ...,
         [ -464.,  -967.,  -856., ...,  -496.,  1020., -1064.],
         [  -93.,     3.,   -25., ...,   -60.,     9.,     4.],
         [ -361.,   431.,   -16., ...,  -128.,  -325.,  -152.]],

        [[ -170.,   486.,   677., ...,  -284.,    42.,   265.],
         [  430.,     0.,   333., ...,  -570.,  -440.,   563.],
         [  -75.,  -908., -1029., ...,   249.,    49., -1012.],
         ...,
         [  389., -1972.,  -541., ...,   312.,  1807., -1609.],
         [  448.,    99.,   480., ...,   493.,  -343.,   508.],
         [ -492.,   701.,     6., ...,  -164.,  -504.,  -160.]],

        [[ -227.,  -495., -1152., ...,   941.,   440.,  -935.],
         [-1405.,   347.,  -788., ...,  1739.,  1529., -1710.],
         [-1115.,  1464.,  1033., ...,   942.,  1169.,   649.],
        

In [22]:
csi[0]

array([[[  472.+1140.j,   181.-1215.j,   966. -831.j, ...,
         -1101. -576.j,  -709.-1054.j,  1088. +595.j],
        [ 1836. +923.j,  -757.-1926.j,   558.-2012.j, ...,
         -2062.  +79.j, -1924. -732.j,  1914. -767.j],
        [ 1825.-1301.j, -2032.-1064.j, -1247.-1868.j, ...,
         -1586.+1581.j, -1906.+1263.j,  -600.-2168.j],
        ...,
        [ -987. -464.j,   445. -967.j,  -677. -856.j, ...,
          -937. -496.j,  -205.+1020.j,   -20.-1064.j],
        [   19.  -93.j,    23.   +3.j,     6.  -25.j, ...,
            33.  -60.j,  -100.   +9.j,    39.   +4.j],
        [  317. -361.j,   131. +431.j,   463.  -16.j, ...,
           459. -128.j,  -376. -325.j,   485. -152.j]],

       [[ -673. -170.j,   475. +486.j,     3. +677.j, ...,
           622. -284.j,   671.  +42.j,  -599. +265.j],
        [ -425. +430.j,   563.   +0.j,   478. +333.j, ...,
           158. -570.j,   385. -440.j,    17. +563.j],
        [ 1047.  -75.j,  -540. -908.j,   -13.-1029.j, ...,
         -1024

In [23]:
csi.dtype

dtype('complex128')

In [24]:
trace = mat_contents["csi_trace"]
csi = trace["csi"][0,0]
mactimer = trace["mactimer"][0,0]


In [26]:
print(csi.shape)
print(csi.dtype)
print(type(csi))


(1, 4, 14, 363)
complex128
<class 'numpy.ndarray'>


In [34]:
from pathlib import Path
import scipy.io as sio

root = Path("../data/RawContinuousRecording")

records = []

for mat_file in root.rglob("*.mat"):
    user_env = mat_file.parts[-3]
    user, env = user_env.split("_")
    device = mat_file.parts[-2]

    mat = sio.loadmat(mat_file)
    csi = mat["csi_trace"]["csi"][0, 0]

    shape = csi.shape  # (N_tx, N_rx, N_subcarriers, N_samples)

    records.append({
        "user": user,
        "env": env,
        "device": device,
        "path": str(mat_file),
        "N_tx": shape[0],
        "N_rx": shape[1],
        "N_subcarriers": shape[2],
        "N_samples": shape[3]
    })

print(records[:3])


[{'user': 'U03', 'env': 'E02', 'device': 'GoveeSmartPlug', 'path': '../data/RawContinuousRecording/U03_E02/GoveeSmartPlug/Continuous_Data_Collection-20250414140718_GoveeSmartPlug_2G.mat', 'N_tx': 1, 'N_rx': 4, 'N_subcarriers': 14, 'N_samples': 462}, {'user': 'U03', 'env': 'E02', 'device': 'GoveeSmartPlug', 'path': '../data/RawContinuousRecording/U03_E02/GoveeSmartPlug/Continuous_Data_Collection-20250414150650_GoveeSmartPlug_2G.mat', 'N_tx': 1, 'N_rx': 4, 'N_subcarriers': 14, 'N_samples': 461}, {'user': 'U03', 'env': 'E02', 'device': 'GoveeSmartPlug', 'path': '../data/RawContinuousRecording/U03_E02/GoveeSmartPlug/Continuous_Data_Collection-20250414140508_GoveeSmartPlug_2G.mat', 'N_tx': 1, 'N_rx': 4, 'N_subcarriers': 14, 'N_samples': 462}]


In [38]:
import pandas as pd

df = pd.DataFrame(records)
df["antenna_config"] = list(zip(df["N_tx"], df["N_rx"]))

print(df.groupby("device")["antenna_config"].unique())
print(df.groupby("device")["N_subcarriers"].unique())


device
AmazonEchoPlus     [(1, 4)]
AmazonEchoShow8    [(1, 4)]
AmazonEchoSpot     [(1, 4)]
AmazonPlug         [(1, 4)]
AppleHomePod       [(1, 4)]
EightreePlug       [(1, 4)]
GoogleNest         [(1, 4)]
GoveeSmartPlug     [(1, 4)]
HealthPod1         [(2, 2)]
HealthPod2         [(2, 2)]
HealthPod3         [(2, 2)]
WyzePlug           [(1, 4)]
Name: antenna_config, dtype: object
device
AmazonEchoPlus     [14]
AmazonEchoShow8    [14]
AmazonEchoSpot     [14]
AmazonPlug         [14]
AppleHomePod       [14]
EightreePlug       [14]
GoogleNest         [14]
GoveeSmartPlug     [14]
HealthPod1         [58]
HealthPod2         [58]
HealthPod3         [58]
WyzePlug           [14]
Name: N_subcarriers, dtype: object


This is great. Each device has either 1 * 4 or 2 * 2 tx, rx pairs which means we have a single set size of 4 total pairings. With the 14 vs 58 subcarriers, we can try to interpolate and use the higher resolution (58)

In [41]:
mat_contents = sio.loadmat("../data/RawContinuousRecording/U01_E01/AmazonEchoPlus/Continuous_Data_Collection-20250509134712_AmazonEchoPlus_5G.mat")
csi = mat_contents["csi_trace"]["csi"][0, 0]

In [ ]:
csi.shape # (n_tx, n_rx, n_sc, n_t)

(1, 4, 14, 363)

In [43]:
n_tx, n_rx, n_sc, n_t = csi.shape
csi = csi.reshape(n_tx * n_rx, n_sc, n_t)

In [ ]:
csi.shape # (n_tx * n_rx, n_sc, n_t)

(4, 14, 363)

In [45]:
csi

array([[[  472.+1140.j,   181.-1215.j,   966. -831.j, ...,
         -1101. -576.j,  -709.-1054.j,  1088. +595.j],
        [ 1836. +923.j,  -757.-1926.j,   558.-2012.j, ...,
         -2062.  +79.j, -1924. -732.j,  1914. -767.j],
        [ 1825.-1301.j, -2032.-1064.j, -1247.-1868.j, ...,
         -1586.+1581.j, -1906.+1263.j,  -600.-2168.j],
        ...,
        [ -987. -464.j,   445. -967.j,  -677. -856.j, ...,
          -937. -496.j,  -205.+1020.j,   -20.-1064.j],
        [   19.  -93.j,    23.   +3.j,     6.  -25.j, ...,
            33.  -60.j,  -100.   +9.j,    39.   +4.j],
        [  317. -361.j,   131. +431.j,   463.  -16.j, ...,
           459. -128.j,  -376. -325.j,   485. -152.j]],

       [[ -673. -170.j,   475. +486.j,     3. +677.j, ...,
           622. -284.j,   671.  +42.j,  -599. +265.j],
        [ -425. +430.j,   563.   +0.j,   478. +333.j, ...,
           158. -570.j,   385. -440.j,    17. +563.j],
        [ 1047.  -75.j,  -540. -908.j,   -13.-1029.j, ...,
         -1024

In [47]:
mag = np.abs(csi)
amp = np.angle(csi)

print(mag, amp)

[[[1233.84926146 1228.40791271 1274.25154503 ... 1242.56871037
   1270.27437981 1240.06814329]
  [2054.95133762 2069.42624899 2087.94348583 ... 2063.51278164
   2058.54317419 2061.96144484]
  [2241.25545175 2293.71314684 2245.98152263 ... 2239.40996693
   2286.48310731 2249.49416536]
  ...
  [1090.62596705 1064.47827596 1091.35924425 ... 1060.18158822
   1040.39655901 1064.18795332]
  [  94.9210198    23.19482701   25.70992026 ...   68.47627326
    100.40418318   39.20459157]
  [ 480.4268935   450.46864486  463.2763754  ...  476.51337862
    496.99195165  508.26075985]]

 [[ 694.13903506  679.57413135  677.00664694 ...  683.76896683
    672.31317107  655.00076336]
  [ 604.58663564  563.          582.55729332 ...  591.49302616
    584.6580197   563.25660227]
  [1049.68280923 1056.43930256 1029.08211529 ... 1053.83917179
   1083.10895112 1055.53019853]
  ...
  [2005.09600768 2007.33878556 2025.58263223 ... 2003.44328595
   2008.13968638 1991.77232635]
  [ 518.98747576  495.0010101   481.

In [50]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [59]:
from load.dataset import CSIDataset
from load.dataloader import get_loaders

In [60]:
dataset = CSIDataset()

Successfully found task directory: ../data/BreathingDetection
Using split: train_id
Loaded 69996 samples for BreathingDetection - train_id


In [61]:
dataset[0][0].shape

torch.Size([1, 500, 232])

In [63]:
loader = get_loaders()
train_loader = loader["loaders"]["train"]

for inputs, _ in train_loader:
    print(inputs.shape, inputs.mean(), inputs.std(), inputs.min(), inputs.max())
    break

Using provided task directory ../data/BreathingDetection
Using provided task directory: ../data/BreathingDetection
Using split: train_id
Loaded 69996 samples for BreathingDetection - train_id
Loaded 69996 samples for BreathingDetection - train_id
Using provided task directory ../data/BreathingDetection
Using provided task directory: ../data/BreathingDetection
Using split: val_id
Loaded 14997 samples for BreathingDetection - val_id
Loaded 14997 samples for BreathingDetection - val_id
Using provided task directory ../data/BreathingDetection
Using provided task directory: ../data/BreathingDetection
Using split: test_easy_id
Loaded 5666 samples for BreathingDetection - test_easy_id
Loaded 5666 samples for BreathingDetection - test_easy_id
Using provided task directory ../data/BreathingDetection
Using provided task directory: ../data/BreathingDetection
Using split: test_medium_id
Loaded 4221 samples for BreathingDetection - test_medium_id
Loaded 4221 samples for BreathingDetection - test_me

In [ ]:
from model.models import MaskedTimesFormer1D, TimesFormer1D
import torch

In [ ]:
# Build pretrained model and load weights
pretrained = MaskedTimesFormer1D(win_len=500, feature_size=232)
pretrained.load_state_dict(torch.load("encoder_weights.pt"), strict=False)

# Build classifier
classifier = TimesFormer1D(pretrained, num_classes=2)